dist: trusty

language: php

php:
  - 7.1

node_js:
  - "6"

env:
  matrix:
    - COMPOSER_FLAGS=""

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer config github-oauth.github.com ${GITHUB_TOKEN}
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover
